# Generated by Django 5.2.11 on 2026-02-22 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authuser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
