# Generated by Django 5.2.11 on 2026-03-29 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizers', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
