# Generated by Django 5.2.4 on 2026-02-15 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizers', '0002_organizationprofile_image'),
        ('users', '0002_volunteerprofile_image'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('volunteer', 'opportunity')},
        ),
    ]
