# Generated by Django 5.2.4 on 2026-02-15 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizers', '0003_alter_application_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationprofile',
            name='image',
            field=models.ImageField(blank=True, default='default/avatar.png', upload_to='organization/'),
        ),
    ]
