# Generated by Django 5.2.11 on 2026-02-22 19:22

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizers', '0005_application_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='end_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='opportunity',
            name='location',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='opportunity',
            name='slots_available',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='slots_filled',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='start_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organizationprofile',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organizationprofile',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='organizationprofile',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number (10-15 digits, optional +).', regex='^\\+?\\d{10,15}$')]),
        ),
        migrations.AddField(
            model_name='organizationprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organizationprofile',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
