# Generated by Django 5.2.11 on 2026-03-01 12:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizers', '0006_opportunity_end_date_opportunity_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opportunity',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
