# Generated by Django 5.2.11 on 2026-03-01 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizers', '0007_alter_opportunity_end_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opportunity',
            old_name='slots_available',
            new_name='total_slots',
        ),
    ]
