# Generated by Django 5.2.11 on 2026-03-08 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizers', '0009_opportunity_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('accepted', 'accepted'), ('rejected', 'rejected'), ('withdrawn', 'withdrawn')], default='pending', max_length=20),
        ),
    ]
