# Generated by Django 5.2.11 on 2026-03-22 06:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('organizers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bio', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, default='default/avatar.png', upload_to='volunteer/')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number (10-15 digits, optional +).', regex='^\\+?\\d{10,15}$')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='authentication.authuser')),
            ],
            options={
                'db_table': 'VolunteerProfile',
            },
        ),
        migrations.CreateModel(
            name='OpportunityFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='organizers.opportunity')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunity_feedbacks', to='users.volunteerprofile')),
            ],
            options={
                'db_table': 'OpportunityFeedback',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['opportunity', '-created_at'], name='Opportunity_opportu_795794_idx')],
                'constraints': [models.UniqueConstraint(fields=('opportunity', 'volunteer'), name='unique_feedback_per_volunteer')],
            },
        ),
    ]
