# Generated by Django 5.2.4 on 2026-02-15 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerprofile',
            name='image',
            field=models.ImageField(blank=True, default='default/avatar.png', upload_to='volunteer/'),
        ),
    ]
