# Generated by Django 5.2.11 on 2026-03-29 12:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteerprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number (+CountryCode-Number, where number is 10-15 digits).', regex='^\\+\\d{1,3}-\\d{10,15}$')]),
        ),
    ]
