# Generated by Django 5.2.11 on 2026-02-22 19:22

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_volunteerprofile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='volunteerprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number (10-15 digits, optional +).', regex='^\\+?\\d{10,15}$')]),
        ),
    ]
